version: "25.0.2"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: facerecog:latest
    container_name: facedetection-dtr
    command: python manage.py runserver 0.0.0.0:8000











